# Generated by Django 4.2.17 on 2025-01-13 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPrediction',
        ),
    ]
