# Generated by Django 4.2.17 on 2025-01-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0005_delete_userprediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='SleepDisorderPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
                ('age', models.PositiveIntegerField()),
                ('occupation', models.CharField(max_length=50)),
                ('sleep_duration', models.FloatField()),
                ('quality_of_sleep', models.PositiveIntegerField()),
                ('physical_activity', models.PositiveIntegerField()),
                ('stress_level', models.PositiveIntegerField()),
                ('bmi_category', models.CharField(max_length=20)),
                ('blood_pressure', models.CharField(max_length=20)),
                ('heart_rate', models.PositiveIntegerField()),
                ('daily_steps', models.PositiveIntegerField()),
                ('prediction_result', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
