# Generated by Django 4.2.17 on 2025-05-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sleepdisorderprediction',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='sleepdisorderprediction',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sleepdisorderprediction',
            name='blood_pressure',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='sleepdisorderprediction',
            name='daily_steps',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sleepdisorderprediction',
            name='heart_rate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sleepdisorderprediction',
            name='physical_activity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sleepdisorderprediction',
            name='prediction_result',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='sleepdisorderprediction',
            name='quality_of_sleep',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sleepdisorderprediction',
            name='stress_level',
            field=models.IntegerField(),
        ),
    ]
